apiVersion: v1
kind: ConfigMap
metadata:
  name: sourcecode-editor-config
data:
  config.json: |
    {
      "OPENTELEMETRY_COLLECTOR_HTTP_TRACES": "12",
      "OPENTELEMETRY_COLLECTOR_HTTP_METRICS": "7",
      "OPENTELEMETRY_COLLECTOR_HTTP_LOGS": "",
      "OPENTELEMETRY_COLLECTOR_EXPORT_LOGS_INTERVAL_SECONDS": "60",
      "OPENTELEMETRY_COLLECTOR_EXPORT_METRICS_INTERVAL_SECONDS": "60",
      "OPENTELEMETRY_COLLECT_AUTHORIZATION_HEADER": ""
    }
