apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../sourcecode-editor

patches:
  - target:
      kind: Service
      name: sourcecode-editor
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: sourcecode-editor
      spec:
        type: NodePort
